name: Android CI

on: 
  push:
    branches:
      - dev
      - 'releases/**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'assets/shaders/**'
      - '*.sh'
      - '*.bat'
jobs:
  build:

    runs-on: windows-2022
    env:
      SDK_VERSION: 1.3.280.0
    steps:
    - uses: actions/setup-java@v4
      with:
        java-version: '11'
    - uses: actions/checkout@v4
    - name: Compile vcpkg dependencies
      run: |
        vcpkg_android.bat
      shell: cmd
    - name: Compile gkNextRenderer
      run: |
        build_android.bat
      shell: cmd
