name: Android CI

on: 
  push:
    branches:
      - dev
      - 'releases/**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'assets/shaders/**'
      - '*.sh'
      - '*.bat'
jobs:
  build:

    runs-on: windows-2022
    env:
      SDK_VERSION: 1.3.280.0
    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: actions/checkout@v4
    - name: Compile vcpkg dependencies
      run: |
        vcpkg_android.bat
      shell: cmd
    - name: Download Vulkan SDK
      run: Invoke-WebRequest "https://sdk.lunarg.com/sdk/download/${env:SDK_VERSION}/windows/vulkan_sdk.exe?Human=true" -OutFile vulkan_sdk.exe -v
    - name: Install Vulkan SDK
      run: .\vulkan_sdk.exe --accept-licenses --default-answer --confirm-command install
      shell: cmd
    - name: Compile gkNextRenderer
      run: |
        set VULKAN_SDK=C:\VulkanSDK\%SDK_VERSION%
        build_android.bat
      shell: cmd
