name: Android CI Linux

on: 
  push:
    branches:
      - dev
      - 'releases/**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'assets/shaders/**'
      - '*.sh'
      - '*.bat'

jobs:
  build:

    runs-on: ubuntu-22.04
    env: 
      SDK_VERSION: 1.3.280
    
    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: actions/checkout@v4
    - name: Compile vcpkg dependencies
      run: ./vcpkg_android.sh
