name: Android CI

on: 
  pull_request:
      branches: [main]
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - '.github/workflows/android.yml'
      - 'src/**'
      - 'assets/shaders/**'
      - '*.sh'
      - '*.bat'
      - '**/CMakeLists.txt'
jobs:
  build:

    runs-on: windows-2022
    env: 
      SDK_VERSION: 1.3.280
    steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: actions/checkout@v4

    - name: Restore cached Primes
      id: cache-primes-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          build/vcpkg.android
        key: ${{ runner.os }}-primes

    - name: Compile vcpkg dependencies
      run: ./vcpkg_android.bat

    - name: Save Primes
      id: cache-primes-save
      uses: actions/cache/save@v4
      with:
        path: |
          build/vcpkg.android
        key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}

    - name: Download Vulkan SDK
      run: Invoke-WebRequest "https://sdk.lunarg.com/sdk/download/${env:SDK_VERSION}/windows/vulkan_sdk.exe?Human=true" -OutFile vulkan_sdk.exe -v

    - name: Install Vulkan SDK
      run: .\vulkan_sdk.exe --accept-licenses --default-answer --confirm-command install
      shell: cmd

    - name: Compile gkNextRenderer
      run: ./build_android.bat